import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { createClient } from 'contentful';
import ReactMarkdown from 'react-markdown';

export async function getStaticProps() {
  // connect to contentful
  const client = createClient({
    space: process.env.CONTENTFUL_SPACE_ID,
    accessToken: process.env.CONTENTFUL_ACCESS_KEY,
  });

  // get the data
  const res = await client.getEntries({ content_type: 'article' });

  return {
    props: {
      articles: res.items
    }
  }
}

export default function Home({ articles }) {
  console.log(articles);

  let articleList = articles.map(a => 
    <div key={a.sys.id}>
      <h1>{a.fields.title}</h1>
      <ReactMarkdown>{a.fields.body}</ReactMarkdown>
    </div>
  );
  console.log(articleList);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Merriweather:ital,wght@0,400;0,700;1,400;1,700&family=Open+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet"/> 
      </Head>

      <main className={styles.main}>
        {articleList}
      </main>

      <footer className={styles.footer}>
        FOOTER
      </footer>
    </div>
  )
}
